apiVersion: v1
kind: Service
metadata:
  name: k8s-backend-service
  namespace: kube-system
spec:
  selector:
    app: k8s-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
