apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-backend-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-basic-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces", "events", "logs", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-role-binding
roleRef:
  kind: ClusterRole
  name: devops-basic-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: k8s-backend-sa
  namespace: kube-system
